### ISSUE TITLE
ci_tools/nox_utils.PowerSession.run2() method does not correctly handle filepaths containing spaces

### ISSUE THREAD

**Issue by mchaaler** [smarie/mkdocs-gallery#31]
This makes the call to `coverage --junitxml={test_xml} --html={test_html}` crash if `test_xml` and `test_html` filepaths contain spaces.

Possible fixes:
- Use nox legacy `Session.run()` method as in flake8 session
- Improve `PowerSession.run2()` by using [shlex.split](https://docs.python.org/3/library/shlex.html#shlex.split) instead of str.split

By the way, just for information, where does the `ci_tools/nox_utils.py` module come from (no module docstring, no reference or source mentioned)?

**Comment by smarie** [comment]
> By the way, just for information, where does the ci_tools/nox_utils.py module come from (no module docstring, no reference or source mentioned)?

This is my "enhanced nox" :) that I use in all of [my open source python projects](https://github.com/smarie/ALL_OF_THE_ABOVE).

Basically it contains things that are not yet (or will never be) merged into nox, available through the `@power_session` decorator:

 - parametrization grid including python version (this is available now in nox, since python version can now be parametrized, but from what I remember my implem is too tightly coupled with the item below).
 - conda or pip installation with "do not install" parameter for some of the runs
 - ability to log each session in a file (in the .nox/logs folder) so as to easily find back the failed ones afterwards (see https://github.com/theacodes/nox/issues/409 , I had originally planned to make a PR including my code but did not yet find the time ... )

**Comment by mchaaler** [comment]
Thanks for the explanation @smarie!

The second proposal is really simple, in fact, and helps improving your 'enhanced nox' module. Reversing to nox legacy `Session.run()` would be kind of a step backwards.
However correcting the run2 method is not enough: one still has to check and correct each call to quote every path in the command string.

Just submitted PR #35 that takes care of both aspects.

**Comment by smarie** [comment]
Fixed by #35 , thanks @mchaaler !
