### ISSUE TITLE
Issue with header in README.md

### ISSUE THREAD

**Issue by AntoineD** [smarie/mkdocs-gallery#85]
When a `README.md` has a header (like a licence header) as a html comment, like so with one of mkdocs gallery's projects examples `docs/examples/no_output/README.md`:
```markdown
<!--
  Header here.
-->
## No image output examples

This section gathers examples which don't produce any figures. Some examples
only output to standard output, others demonstrate how Mkdocs-Gallery handles
examples with errors.
```

The rendering is broken:
![Screenshot from 2023-11-22 12-20-38](https://github.com/smarie/mkdocs-gallery/assets/433696/8f0a02b6-cb31-4805-8a87-eaccb2ca3a0e)

**Comment by smarie** [comment]
Hello @AntoineD , thanks for reporting this issue ! 

This is strange: `mkdocs` is supposed to correctly tackle markdown pages containing such a header. 

When I try to reproduce the issue, the page concatenating all README.md displays correctly (on the right), including the html comment (if I look at the source). The problem seems "just" that the name of the subgallery is not correctly detected

![image](https://github.com/smarie/mkdocs-gallery/assets/3236794/51010179-3a1c-466d-890a-6b00873542bc)

Do you confirm ? If so, the fix should improve the subgallery name detection script (making it robust to the presence of one or several leading HTML elements), but not remove the HTML comment and users who wrote it might want it to eventually be integrated in the final generated html.

**Comment by AntoineD** [comment]
Hello @smarie,

I'm surprised that you can not reproduce the same rendering. I obtained it by running `nox -s docs` on my PR without the fix.

Anyway I agree that the comment shall not be removed in the end, I'll change that.

**Comment by smarie** [comment]
Hi @AntoineD , yes it was done 0.8.0 and 0.9.0 integrate it :)
