### ISSUE TITLE
Support for async examples?

### ISSUE THREAD

**Issue by pmeier** [smarie/mkdocs-gallery#88]
When I'm inside a `jupyter` notebook, the following is a valid code block:

```python
import asyncio
import time

start = time.time()
await asyncio.sleep(1)
stop = time.time()
f"I waited for {stop - start} seconds!"
```

However, if you put this inside a gallery script and try to run this, you'll hit 

```
SyntaxError: 'await' outside function
```

This is expected, since we are currently not inside an `async` context. The difference to `jupyter` notebooks is that they have an `async` event loop in the background.

I would like to have the same convenience for example scripts as well. Without, it is a pain to write example that have `async` code in it. Plus it will become nightmarish if one at the same time also wants to support the downloadable jupyter notebook.

If this is something that we want, I'm happy to help designing and implementing this feature.

**Comment by pmeier** [comment]
> Do you know what is the logic implemented by `jupyter` for async blocks ?

I don't. Will have to dig as well. Will get back to you when I have something.

**Comment by smarie** [comment]
Ok. From a blog post I read, it seems that behind the scenes it uses the PR I mentioned above

**Comment by pmeier** [comment]
I think your finding is spot on. Here are some relevant functions that we in some capacity probably need as well:

- [`_should_be_async`](https://github.com/ipython/ipython/blob/dd7f1e1894395f59649a84f94af8c9710202b08f/IPython/core/async_helpers.py#L139): Detect if a block of code need to be wrapped in an `async def`
- [`should_run_async`](https://github.com/ipython/ipython/blob/dd7f1e1894395f59649a84f94af8c9710202b08f/IPython/core/interactiveshell.py#L3114): Return whether a cell should be run asynchronously via a coroutine runner

(will update this list when I find more)

**Comment by pmeier** [comment]
Ping @smarie

**Comment by smarie** [comment]
Thanks @pmeier , this is a very nicely structured post ! 

I agree with *everything* you wrote !. My only comments are

> If it is not possible to have a feature as per-file and per-block level, my vote is out for only having the per-file one.

We have built-in mechanisms for both global config and per-block config, similar to the ones in [sphinx-gallery](https://sphinx-gallery.github.io/stable/configuration.html#adding-line-numbers-to-examples), you can see an example here : https://github.com/smarie/mkdocs-gallery/blob/main/docs/examples/plot_4_choose_thumbnail.py#L32 where the `# mkdocs_gallery_thumbnail_number = 2` comment is anywhere in the code block and is detected and removed at gallery example parsing time.

> One downside of the approach detailed above is that the gallery script itself is not executable by Python since our magic async handling only happens when building the documentation. I always found this to be a nice feature, albeit not a crucial one (LMK if you think different here). One possibility to get this back would be to provide something like __async_wrapper__ importable as part of mkdocs_gallery. Meaning, instead of just marking a code block as async with a feature flag, users could actually make it async. We could still perform all magic we need if we detect it.

This is a very good point. I myself make great use of this feature for debugging. Even if using `mkdocs build` or `mkdocs serve` in debug mode is usually a good enough workaround, there is no fast shortcut in the IDE for this so one has to remember how to configure the IDE run configuration to launch mkdocs entrypoint.
I like the workaround you propose and to be honest I cannot think of a better one as for now. Even if this workaround works great, it should still be a workaround IMO, and users will probably remove the `__async_wrapper__` once debugging session is over. So it does not replace the config, global or local to code block.

My last comment is due to my lack of memory about how event loops work in ipython/jupyter. Are all async code blocks run on the same event loop or is this a distinct one for every async code block in the same file ? I guess that across different files the answer is "different loops", but inside the same file I wonder what is the jupyter implementation. Yet.... does it matter ? Not sure as well :)

Anyway with the above plan you can safely progress towards a PR at this point.
Thanks again for the great proposal!
